name: SquareLottery
version: @pom.version@
api: [1.0.9]
main: xyz.lightsky.squarelottery.SquareLottery
author: iGxnon
commands:
  sly:
    usage: /sly
    permission: sly.command.SquareLottery
permissions:
  sly.command.SquareLottery:
    default: true