name: SquareLottery
version: 1.0-SNAPSHOT
api: [1.0.9]
main: cc.igxnon.squarelottery.SquareLottery
author: iGxnon
permissions:
  addLottery.command.SquareLottery:
    default: op
  delLottery.command.SquareLottery:
    default: op